-- =============================================
-- AUTH TABLES — Manpower Contract Management
-- Run this FIRST before any other scripts
-- =============================================

-- 1. MST_DEPARTMENT
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MST_DEPARTMENT]'))
BEGIN
CREATE TABLE [dbo].[MST_DEPARTMENT] (
    DEPARTMENT_ID   INT IDENTITY(1,1) NOT NULL,
    DEPARTMENT_NAME NVARCHAR(200)     NOT NULL,
    IS_ACTIVE       BIT               NOT NULL DEFAULT 1,
    IS_DELETED      BIT               NOT NULL DEFAULT 0,
    C_USER_ID       INT               NULL,
    C_DATETIME      DATETIME          NOT NULL DEFAULT GETDATE(),
    M_USER_ID       INT               NULL,
    M_DATETIME      DATETIME          NULL,
    CONSTRAINT PK_MST_DEPARTMENT PRIMARY KEY CLUSTERED (DEPARTMENT_ID)
);
END
GO

-- 2. MST_ROLE
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MST_ROLE]'))
BEGIN
CREATE TABLE [dbo].[MST_ROLE] (
    ROLE_ID         INT IDENTITY(1,1) NOT NULL,
    ROLE_NAME       NVARCHAR(100)     NOT NULL,
    DESCRIPTION     NVARCHAR(500)     NULL,
    IS_ACTIVE       BIT               NOT NULL DEFAULT 1,
    IS_DELETED      BIT               NOT NULL DEFAULT 0,
    C_USER_ID       INT               NULL,
    C_DATETIME      DATETIME          NOT NULL DEFAULT GETDATE(),
    M_USER_ID       INT               NULL,
    M_DATETIME      DATETIME          NULL,
    CONSTRAINT PK_MST_ROLE PRIMARY KEY CLUSTERED (ROLE_ID)
);
END
GO

-- 3. MST_USER
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MST_USER]'))
BEGIN
CREATE TABLE [dbo].[MST_USER] (
    USER_ID         INT IDENTITY(1,1) NOT NULL,
    FULL_NAME       NVARCHAR(200)     NOT NULL,
    EMAIL           NVARCHAR(200)     NOT NULL,
    PASSWORD_HASH   NVARCHAR(500)     NOT NULL,
    PASSWORD_SALT   NVARCHAR(500)     NOT NULL,
    ROLE_ID         INT               NOT NULL,
    DEPARTMENT_ID   INT               NULL,
    IS_ACTIVE       BIT               NOT NULL DEFAULT 1,
    IS_DELETED      BIT               NOT NULL DEFAULT 0,
    LAST_LOGIN_DT   DATETIME          NULL,
    C_USER_ID       INT               NULL,
    C_DATETIME      DATETIME          NOT NULL DEFAULT GETDATE(),
    M_USER_ID       INT               NULL,
    M_DATETIME      DATETIME          NULL,
    CONSTRAINT PK_MST_USER      PRIMARY KEY CLUSTERED (USER_ID),
    CONSTRAINT FK_USER_ROLE     FOREIGN KEY (ROLE_ID) REFERENCES MST_ROLE(ROLE_ID),
    CONSTRAINT FK_USER_DEPT     FOREIGN KEY (DEPARTMENT_ID) REFERENCES MST_DEPARTMENT(DEPARTMENT_ID),
    CONSTRAINT UQ_USER_EMAIL    UNIQUE (EMAIL)
);
END
GO

-- 4. MST_MODULE (with PARENT_MODULE_ID for collapsible groups)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MST_MODULE]'))
BEGIN
CREATE TABLE [dbo].[MST_MODULE] (
    MODULE_ID        INT IDENTITY(1,1) NOT NULL,
    MODULE_CODE      NVARCHAR(50)      NOT NULL,
    MODULE_NAME      NVARCHAR(100)     NOT NULL,
    PARENT_MODULE_ID INT               NULL,
    ICON_CLASS       NVARCHAR(100)     NULL,
    URL_PATH         NVARCHAR(200)     NULL,
    DISPLAY_ORDER    INT               NOT NULL DEFAULT 0,
    IS_ACTIVE        BIT               NOT NULL DEFAULT 1,
    CONSTRAINT PK_MST_MODULE    PRIMARY KEY CLUSTERED (MODULE_ID),
    CONSTRAINT UQ_MODULE_CODE   UNIQUE (MODULE_CODE),
    CONSTRAINT FK_MODULE_PARENT FOREIGN KEY (PARENT_MODULE_ID) REFERENCES MST_MODULE(MODULE_ID)
);
END
GO

-- 5. MST_ROLE_PERMISSION (Create / Disable / View / Update / Download)
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MST_ROLE_PERMISSION]'))
BEGIN
CREATE TABLE [dbo].[MST_ROLE_PERMISSION] (
    ROLE_PERMISSION_ID INT IDENTITY(1,1) NOT NULL,
    ROLE_ID            INT               NOT NULL,
    MODULE_ID          INT               NOT NULL,
    CAN_CREATE         BIT               NOT NULL DEFAULT 0,
    CAN_DISABLE        BIT               NOT NULL DEFAULT 0,
    CAN_VIEW           BIT               NOT NULL DEFAULT 0,
    CAN_UPDATE         BIT               NOT NULL DEFAULT 0,
    CAN_DOWNLOAD       BIT               NOT NULL DEFAULT 0,
    C_USER_ID          INT               NULL,
    C_DATETIME         DATETIME          NOT NULL DEFAULT GETDATE(),
    M_USER_ID          INT               NULL,
    M_DATETIME         DATETIME          NULL,
    CONSTRAINT PK_MST_ROLE_PERMISSION PRIMARY KEY CLUSTERED (ROLE_PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE   FOREIGN KEY (ROLE_ID)   REFERENCES MST_ROLE(ROLE_ID),
    CONSTRAINT FK_RP_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MST_MODULE(MODULE_ID),
    CONSTRAINT UQ_ROLE_MODULE UNIQUE (ROLE_ID, MODULE_ID)
);
END
GO

-- 6. TRN_AUDIT_LOG
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TRN_AUDIT_LOG]'))
BEGIN
CREATE TABLE [dbo].[TRN_AUDIT_LOG] (
    LOG_ID          INT IDENTITY(1,1) NOT NULL,
    USER_ID         INT               NULL,
    MODULE          NVARCHAR(100)     NULL,
    ACTION          NVARCHAR(100)     NULL,
    DESCRIPTION     NVARCHAR(1000)    NULL,
    IP_ADDRESS      NVARCHAR(50)      NULL,
    USER_AGENT      NVARCHAR(500)     NULL,
    LOG_DATETIME    DATETIME          NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_TRN_AUDIT_LOG PRIMARY KEY CLUSTERED (LOG_ID)
);
END
GO

-- INDEXES
CREATE NONCLUSTERED INDEX IX_USER_ROLE ON MST_USER(ROLE_ID) WHERE IS_DELETED = 0;
GO
CREATE NONCLUSTERED INDEX IX_USER_DEPT ON MST_USER(DEPARTMENT_ID) WHERE IS_DELETED = 0;
GO
CREATE NONCLUSTERED INDEX IX_USER_EMAIL ON MST_USER(EMAIL) WHERE IS_DELETED = 0;
GO
CREATE NONCLUSTERED INDEX IX_RP_ROLE ON MST_ROLE_PERMISSION(ROLE_ID);
GO
CREATE NONCLUSTERED INDEX IX_MODULE_PARENT ON MST_MODULE(PARENT_MODULE_ID);
GO

PRINT '✅ Auth tables created successfully.';
GO
