-- ============================================================
-- MANPOWER CONTRACT MANAGEMENT - TABLE SCRIPTS
-- SQL Server 2016+
-- ============================================================

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- ── LOOKUP TABLES ───────────────────────────────────────────

CREATE TABLE GROUP_COMPANY_MST (
    GROUP_COMPANY_ID    INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    GROUP_COMPANY_NAME  NVARCHAR(200)   NOT NULL,
    IS_DELETED          BIT             NOT NULL DEFAULT 0,
    C_USER_ID           INT             NOT NULL,
    C_DATETIME          DATETIME        NOT NULL DEFAULT GETDATE(),
    M_USER_ID           INT             NULL,
    M_DATETIME          DATETIME        NULL
)
GO

CREATE TABLE PLANT_MST (
    PLANT_ID            INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    PLANT_NAME          NVARCHAR(200)   NOT NULL,
    GROUP_COMPANY_ID    INT             NOT NULL,
    PLANT_COUNTRY       NVARCHAR(100)   NULL,
    IS_DELETED          BIT             NOT NULL DEFAULT 0,
    C_USER_ID           INT             NOT NULL,
    C_DATETIME          DATETIME        NOT NULL DEFAULT GETDATE(),
    M_USER_ID           INT             NULL,
    M_DATETIME          DATETIME        NULL,
    CONSTRAINT FK_PLANT_GROUPCOMPANY FOREIGN KEY (GROUP_COMPANY_ID) REFERENCES GROUP_COMPANY_MST(GROUP_COMPANY_ID)
)
GO

CREATE TABLE SUPPLIER_MST (
    SUPPLIER_ID             INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ERP_SUPPLIER_NAME       NVARCHAR(200)   NOT NULL,
    GLOBAL_SUPPLIER_NAME    NVARCHAR(200)   NULL,
    SUPPLIER_COUNTRY        NVARCHAR(100)   NULL,
    IS_DELETED              BIT             NOT NULL DEFAULT 0,
    C_USER_ID               INT             NOT NULL,
    C_DATETIME              DATETIME        NOT NULL DEFAULT GETDATE(),
    M_USER_ID               INT             NULL,
    M_DATETIME              DATETIME        NULL
)
GO

CREATE TABLE CURRENCY_MST (
    CURRENCY_ID     INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    CURRENCY_CODE   NVARCHAR(10)    NOT NULL,
    CURRENCY_NAME   NVARCHAR(100)   NULL,
    IS_DELETED      BIT             NOT NULL DEFAULT 0
)
GO

-- ── MAIN TABLE ──────────────────────────────────────────────

CREATE TABLE MANPOWER_CONTRACT_MST (
    CONTRACT_ID             INT             NOT NULL IDENTITY(1,1) PRIMARY KEY,
    YEAR                    INT             NOT NULL,
    MONTH                   NVARCHAR(20)    NOT NULL,
    RCO                     NVARCHAR(100)   NOT NULL,
    DIVISION                NVARCHAR(200)   NOT NULL,
    GROUP_COMPANY_ID        INT             NOT NULL,
    PLANT_ID                INT             NOT NULL,
    PLANT_COUNTRY           NVARCHAR(100)   NULL,
    SUPPLIER_ID             INT             NOT NULL,
    GLOBAL_SUPPLIER_NAME    NVARCHAR(200)   NULL,
    SUPPLIER_NAME_REMARKS   NVARCHAR(500)   NULL,
    SUPPLIER_COUNTRY        NVARCHAR(100)   NULL,
    ANNUAL_SUPPLIER_SPEND   DECIMAL(18,2)   NOT NULL DEFAULT 0,
    CURRENCY_ID             INT             NOT NULL,
    CONTRACTED              NVARCHAR(5)     NOT NULL DEFAULT 'No',   -- Yes / No
    WORKER_TYPE             NVARCHAR(100)   NULL,
    CONTRACTED_START_DATE   DATE            NOT NULL,
    CONTRACTED_END_DATE     DATE            NOT NULL,
    IS_DELETED              BIT             NOT NULL DEFAULT 0,
    C_USER_ID               INT             NOT NULL,
    C_DATETIME              DATETIME        NOT NULL DEFAULT GETDATE(),
    M_USER_ID               INT             NULL,
    M_DATETIME              DATETIME        NULL,
    CONSTRAINT FK_CONTRACT_GROUPCOMPANY FOREIGN KEY (GROUP_COMPANY_ID) REFERENCES GROUP_COMPANY_MST(GROUP_COMPANY_ID),
    CONSTRAINT FK_CONTRACT_PLANT        FOREIGN KEY (PLANT_ID)         REFERENCES PLANT_MST(PLANT_ID),
    CONSTRAINT FK_CONTRACT_SUPPLIER     FOREIGN KEY (SUPPLIER_ID)      REFERENCES SUPPLIER_MST(SUPPLIER_ID),
    CONSTRAINT FK_CONTRACT_CURRENCY     FOREIGN KEY (CURRENCY_ID)      REFERENCES CURRENCY_MST(CURRENCY_ID)
)
GO

-- ── INDEXES ─────────────────────────────────────────────────
CREATE INDEX IX_CONTRACT_YEAR_MONTH    ON MANPOWER_CONTRACT_MST (YEAR, MONTH)
CREATE INDEX IX_CONTRACT_SUPPLIER      ON MANPOWER_CONTRACT_MST (SUPPLIER_ID)
CREATE INDEX IX_CONTRACT_PLANT         ON MANPOWER_CONTRACT_MST (PLANT_ID)
CREATE INDEX IX_CONTRACT_GROUPCOMPANY  ON MANPOWER_CONTRACT_MST (GROUP_COMPANY_ID)
GO
